### PR TITLE
Fix selectEditor to stop editing after value change

### LINKED ISSUE #3653: `SelectEditor` requires user to blur grid cell after input commit to set value on record
When editing a grid cell with a select editor, the user would naturally expect a just-selected value to commit to the StoreRecord - it's been "committed" to the input and in a form context would have been set.  But our inline editing grid requires the grid cell to be blurred for the new value to take.  

We would like to avoid this for select in particular.  (Could be an option if needed, but I don't know if there is any reason to maintain the current behavior.)

https://github.com/xh/hoist-react/assets/225806/97c3690a-ba71-40fc-b0f4-d68dfa803bf1

### PR DESCRIPTION
**Pull request by saba-mo**
Resolves #3653

Hoist P/R Checklist
-------------------

**Pull request authors:** Review and check off the below. Items that do not apply can also be
checked off to indicate they have been considered. If unclear if a step is relevant, please leave
unchecked and note in comments.

- [x] Caught up with `develop` branch as of last change.
- [x] Added CHANGELOG entry, or determined not required.
- [x] Reviewed for breaking changes, added `breaking-change` label + CHANGELOG if so.
- [x] Updated doc comments / prop-types, or determined not required.
- [x] Reviewed and tested on Mobile, or determined not required.
- [x] Created Toolbox branch / PR, or determined not required.

**If your change is still a WIP**, please use the "Create draft pull request" option in the split
button below to indicate it is not ready yet for a final review.

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to
> collapse multiple intermediate commits into a single commit representing the overall feature
> change. This helps keep the commit log clean and easy to scan across releases. PRs containing a
> single commit should be *rebased* when possible.

### CODE REVIEW

File: desktop/cmp/grid/editors/SelectEditor.ts [hunk 1]
```diff
@@ -19,12 +19,19 @@ export const [SelectEditor, selectEditor] = hoistCmp.withFactory<SelectEditorPro
...
     render(props, ref) {
+        const quickEdit = !props.gridModel.fullRowEditing && !props.inputProps.enableMulti;
+
         props = {
             ...props,
             inputProps: {
                 hideDropdownIndicator: true,
                 hideSelectedOptionCheck: true,
                 selectOnFocus: false,
+                onCommit: () => {
```
Comment (lbwexler) [inline desktop/cmp/grid/editors/SelectEditor.ts:30]: just to be clear, if the application supplies an onCommit of its own, that will stomp on this behavior.  Maybe that 's ok, or maybe we want to rework this, so we always call both?

Comment (amcclain) [reply desktop/cmp/grid/editors/SelectEditor.ts:30]: I'd say that's tolerable - I don't imagine that would be common, and you could argue it falls under the general umbrella of "overriding some inputProps might break or change built-in behaviors" with these inputs.

Since it's non critical and is in the right direction (allowing app to override hoist) probably simplest to let it be.  If an app dev wonders why they aren't getting this subtle improvement, we can look here and know what to do :)

File: CHANGELOG.md [hunk 2]
```diff
@@ -36,6 +36,9 @@ for more details.
 
 * Removed support for passing a plain object to the `model` prop of Hoist Components (previously
   deprecated back in v58). Use the `modelConfig` prop instead.
+* Improved `selectEditor` to stop editing when the value changes, rather than when the user clicks
+  away from the cell, making it more intuitive for users. This only occurs in the absence of
+  `GridModel.fullRowEditing` and `Select.enableMulti`.
```
Comment (amcclain) [inline CHANGELOG.md:41]: I'd vote for dropping this last sentence - it's a huge changelog entry already, that that's a bit more detailed than a developer needs in this context
